baseURL = 'http://wesleylong30.netlify.app/'
languageCode = 'en-us'
title = 'Wesley Long'
theme = "gokarna"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about-me"
    name = "About Me"
    url = "/about-me/"
    weight = 2
  
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
  
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  [[menu.tools]]
  identifier = "github"
  pre = "<span data-feather='Github'></span>"
  url = "https://github.com/WesleyL30"
  weight = 6

[params]
  # URL for the avatar on homepage
  avatarURL = "/static/IMG_6967.PNG"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-s"

  # Description to display on homepage
  description = "Software Developer"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["portfolio", "gokarna", "hugo"]

  # Footer text
  footer = "Wesley Long"

    socialIcons = [
      {name = "github", url = "https://github.com/WesleyL30/"},
      {name = "linkedin", url = "https://www.linkedin.com/in/long-wesley/"},
    ]